# Generated by Django 2.1 on 2019-05-13 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastGenre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='url',
        ),
        migrations.AddField(
            model_name='podcast',
            name='art_url_100',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='podcast',
            name='art_url_30',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='podcast',
            name='art_url_60',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='podcast',
            name='art_url_600',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='podcast',
            name='feed_url',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='podcast',
            name='genres',
            field=models.ManyToManyField(related_name='genres', to='account.PodcastGenre'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='primary_genre',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.PodcastGenre'),
            preserve_default=False,
        ),
    ]
