# Generated by Django 2.1 on 2019-05-13 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('account', '0004_auto_20190513_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='podcast',
            options={'verbose_name': 'Podcast', 'verbose_name_plural': 'Podcasts'},
        ),
        migrations.AlterModelOptions(
            name='podcastgenre',
            options={'verbose_name': 'Podcast Genre', 'verbose_name_plural': 'Podcast Genres'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterField(
            model_name='podcastgenre',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='account.PodcastGenre'),
        ),
        migrations.AlterModelTable(
            name='podcast',
            table='podcasts',
        ),
        migrations.AlterModelTable(
            name='podcastgenre',
            table='podcast_genres',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profiles',
        ),
    ]
