# Generated by Django 2.1 on 2019-05-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190513_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='genres',
            field=models.ManyToManyField(related_name='genres_many2many', to='account.PodcastGenre'),
        ),
    ]
