# Generated by Django 2.1 on 2019-05-13 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20190513_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscribes',
            field=models.ManyToManyField(default=None, to='account.Podcast'),
        ),
    ]
