# Generated by Django 2.1 on 2019-05-13 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20190513_2247'),
        ('account', '0005_auto_20190513_2327'),
    ]

    operations = [
    ]
