# Generated by Django 2.1 on 2019-05-14 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_merge_20190513_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcast',
            old_name='art_url_100',
            new_name='image_url',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='art_url_30',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='art_url_60',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='art_url_600',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='primary_genre',
        ),
        migrations.AddField(
            model_name='podcast',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='podcast',
            name='title',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
